Add new pip installation to RAPIDS-Colab install script
rapidsai-community/rapidsai-csp-utils pull request #65
Opened 2022-12-02 19:17 UTC by taureandyernv

- [ ] Adding new script to install pip into env-check.py
- [ ] Added warnings to not continue conda based approach

2022-12-02 19:26 UTC, taureandyernv commented
closes #63
closes #66

2022-12-05 20:17 UTC, beckernick requested changes

2022-12-05 20:17 UTC, beckernick commented on colab/env-check.py
> +  print("""
Why do we need to do this in subprocesses?

Are we able to just link to a fresh Colab notebook that does the necessary steps in a cell?

2022-12-07 12:37 UTC, taureandyernv commented on colab/env-check.py
> +  print("""
We are able to, BUT encapsulating the RAPIDS install in a set of script is an easy way to keep all content across all colab notebooks using the rapids-colab template up to date, despite numerous, behind-the-scenes changes.  If a user took an existing rapids-colab notebook that used the template for the install, from even 2 years ago, they would still get RAPIDS installed once this is updated.  If anything changes in the pip install, we change it here, and the user can still use that same template.

2022-12-13 17:26 UTC, reouvenzana commented
Hello, I just tried your test colab notebook. The installation process is much faster than before, but I can't import any modules other than cudf.

When trying to import cuML, I get a ModuleNotFoundError.

2022-12-28 03:42 UTC, taureandyernv commented
Fix for @reouvenzana 's issue was that I actually had to uncomment out the installs of cuml and cugraph (was testing basic install).  we're good now and I'm merging

2022-12-28 03:42 UTC, merged